name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read                  
  pages: write                 

jobs:
  buildswaggerEditor:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout swagger-editor   
       uses: actions/checkout@v4
       with:
          repository: swagger-api/swagger-editor
          ref:  '3.x'
          path: swagger-editor
       
     - name: Build Swagger Editor
       run: |
         cd swagger-editor
         npm install
         npm start
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v4  
       with:
          publish_dir: ./swagger-editor/dist
