name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read                  
  pages: write      
  id-token: write 
jobs:
  buildswaggerEditor:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout swagger-editor   
       uses: actions/checkout@v4
       with:
          repository: swagger-api/swagger-editor
          ref:  'v4.14.1'
          path: swagger-editor
       
     - name: Build Swagger Editor
       run: |
         cd swagger-editor
         npm install --legacy-peer-deps
         npm run build
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v4  
       with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./swagger-editor/dist
